-- The AI review on the clock: a status column and a poll cursor on
-- `ai_review_runs`, so the reminder tick can read what is still in flight and
-- rotate through it fairly.
--
-- Generated by drizzle-kit from `src/schema.ts`, then EDITED by hand in one
-- place: `status` is added nullable, backfilled from the status each row's
-- payload already carries, and only then made NOT NULL. The generated
-- `ADD COLUMN ... NOT NULL` fails on any table that has rows, and a default
-- would have written the same status onto every run regardless of where it
-- actually got to.
--
-- `last_polled_at` needs no such treatment: it is nullable and stays nullable,
-- because a run nobody has polled yet has no reading to record — and it is
-- precisely the one the clock should reach first, which is why the index carries
-- `NULLS FIRST`. Ordered by `requested_at` instead, a tenancy holding a batch's
-- worth of reviews parked on their findings — a state only a person leaves,
-- never a poll — would fill every batch for ever and the clock would never reach
-- a newer review at all.
--
-- The final schema is exactly what `snapshot.json` records, so the next
-- `db:generate` diffs against the same state drizzle believes this left behind.
-- The D1 adapter carries the same change as `migrations/0004_ai_review_status.sql`.

ALTER TABLE "ai_review_runs" ADD COLUMN "status" text;--> statement-breakpoint
UPDATE "ai_review_runs" SET "status" = "data"->>'status' WHERE "status" IS NULL;--> statement-breakpoint
ALTER TABLE "ai_review_runs" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ai_review_runs" ADD COLUMN "last_polled_at" bigint;--> statement-breakpoint
-- Backfilled from the payload for the rows written before the column existed.
-- Those payloads carry no `lastPolledAt`, so the extraction is null and the run
-- sorts first, which is the right answer: nothing here has been polled since the
-- deployment learnt to record it.
UPDATE "ai_review_runs" SET "last_polled_at" = ("data"->>'lastPolledAt')::bigint;--> statement-breakpoint
-- The reminder tick's AI-review read: what is unsettled in the org it is
-- ticking, least recently polled first.
CREATE INDEX "ai_review_runs_status_idx" ON "ai_review_runs" ("org_id","status","last_polled_at" NULLS FIRST);
