-- The org boundary: a tenancy on every table.
--
-- Generated by drizzle-kit from `src/schema.ts`, then EDITED by hand in three
-- places, because a generated diff cannot know what the rows that already exist
-- should say:
--
--   * every `org_id` is added nullable, backfilled to the deployment's default
--     org, and only then made NOT NULL. Adding it NOT NULL outright fails on any
--     table that has rows, and a nullable tenancy column is one a query can
--     match by accident.
--   * `reviewers.data->>'role'` and `api_keys.role` are backfilled to `admin`.
--     A row written before roles existed belongs to somebody who could already
--     reach every route on this deployment, so narrowing it here would upgrade a
--     working deployment into one whose Configuration screen nobody can open.
--
-- The final schema is exactly what `snapshot.json` records, so the next
-- `db:generate` diffs against the same state drizzle believes this left behind.
-- The D1 adapter carries the same change as `migrations/0003_orgs.sql`.

CREATE TABLE "orgs" (
	"id" text PRIMARY KEY,
	"slug" text NOT NULL CONSTRAINT "orgs_slug_idx" UNIQUE,
	"created_at" bigint NOT NULL,
	"data" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "projects" DROP CONSTRAINT "projects_ref_idx";--> statement-breakpoint
ALTER TABLE "ai_review_runs" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "api_keys" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "api_keys" ADD COLUMN "role" text DEFAULT 'member' NOT NULL;--> statement-breakpoint
ALTER TABLE "attention_requests" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "identities" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "integration_tokens" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "reminders" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "review_commitments" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "review_requests" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "reviewers" ADD COLUMN "org_id" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "org_id" text;--> statement-breakpoint
-- Every row that existed before this migration belongs to the default org,
-- which is the fixed id `@sainte-beuve/contracts` spells as `DEFAULT_ORG_ID`.
-- A deployment that never makes a second org is entirely inside it and
-- behaves exactly as it did.
UPDATE "ai_review_runs" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "api_keys" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "attention_requests" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "identities" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "integration_tokens" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "projects" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "reminders" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "review_commitments" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "review_requests" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "reviewers" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
UPDATE "sessions" SET "org_id" = 'org_default' WHERE "org_id" IS NULL;--> statement-breakpoint
ALTER TABLE "ai_review_runs" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "api_keys" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "attention_requests" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "identities" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "integration_tokens" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "reminders" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "review_commitments" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "review_requests" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "reviewers" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "org_id" SET NOT NULL;--> statement-breakpoint
-- The two role backfills. See the note at the top of this file.
UPDATE "reviewers" SET "data" = "data" || '{"role": "admin"}'::jsonb;--> statement-breakpoint
UPDATE "api_keys" SET "role" = 'admin';--> statement-breakpoint
ALTER TABLE "identities" DROP CONSTRAINT "identities_pkey";--> statement-breakpoint
ALTER TABLE "identities" ADD PRIMARY KEY ("org_id","provider","subject");--> statement-breakpoint
ALTER TABLE "ai_review_runs" DROP CONSTRAINT "ai_review_runs_pkey";--> statement-breakpoint
ALTER TABLE "ai_review_runs" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "api_keys" DROP CONSTRAINT "api_keys_pkey";--> statement-breakpoint
ALTER TABLE "api_keys" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "attention_requests" DROP CONSTRAINT "attention_requests_pkey";--> statement-breakpoint
ALTER TABLE "attention_requests" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "integration_tokens" DROP CONSTRAINT "integration_tokens_pkey";--> statement-breakpoint
ALTER TABLE "integration_tokens" ADD PRIMARY KEY ("org_id","integration_id");--> statement-breakpoint
ALTER TABLE "projects" DROP CONSTRAINT "projects_pkey";--> statement-breakpoint
ALTER TABLE "projects" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "reminders" DROP CONSTRAINT "reminders_pkey";--> statement-breakpoint
ALTER TABLE "reminders" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "review_commitments" DROP CONSTRAINT "review_commitments_pkey";--> statement-breakpoint
ALTER TABLE "review_commitments" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "review_requests" DROP CONSTRAINT "review_requests_pkey";--> statement-breakpoint
ALTER TABLE "review_requests" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "reviewers" DROP CONSTRAINT "reviewers_pkey";--> statement-breakpoint
ALTER TABLE "reviewers" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "sessions_pkey";--> statement-breakpoint
ALTER TABLE "sessions" ADD PRIMARY KEY ("org_id","id");--> statement-breakpoint
DROP INDEX "ai_review_runs_review_idx";--> statement-breakpoint
CREATE INDEX "ai_review_runs_review_idx" ON "ai_review_runs" ("org_id","review_id","requested_at");--> statement-breakpoint
DROP INDEX "api_keys_created_idx";--> statement-breakpoint
CREATE INDEX "api_keys_created_idx" ON "api_keys" ("org_id","created_at");--> statement-breakpoint
DROP INDEX "attention_requests_status_idx";--> statement-breakpoint
CREATE INDEX "attention_requests_status_idx" ON "attention_requests" ("org_id","status","created_at");--> statement-breakpoint
DROP INDEX "identities_reviewer_idx";--> statement-breakpoint
CREATE INDEX "identities_reviewer_idx" ON "identities" ("org_id","reviewer_id");--> statement-breakpoint
DROP INDEX "reminders_review_idx";--> statement-breakpoint
CREATE INDEX "reminders_review_idx" ON "reminders" ("org_id","review_id");--> statement-breakpoint
DROP INDEX "reminders_due_idx";--> statement-breakpoint
CREATE INDEX "reminders_due_idx" ON "reminders" ("org_id","status","due_at");--> statement-breakpoint
DROP INDEX "review_commitments_reviewer_idx";--> statement-breakpoint
CREATE INDEX "review_commitments_reviewer_idx" ON "review_commitments" ("org_id","reviewer_id","created_at");--> statement-breakpoint
DROP INDEX "review_requests_status_idx";--> statement-breakpoint
CREATE INDEX "review_requests_status_idx" ON "review_requests" ("org_id","status","created_at");--> statement-breakpoint
DROP INDEX "review_requests_pr_idx";--> statement-breakpoint
CREATE INDEX "review_requests_pr_idx" ON "review_requests" ("org_id","pr_owner","pr_repo","pr_number");--> statement-breakpoint
DROP INDEX "sessions_reviewer_idx";--> statement-breakpoint
CREATE INDEX "sessions_reviewer_idx" ON "sessions" ("org_id","reviewer_id");--> statement-breakpoint
DROP INDEX "sessions_expiry_idx";--> statement-breakpoint
CREATE INDEX "sessions_expiry_idx" ON "sessions" ("org_id","expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "projects_ref_idx" ON "projects" ("org_id","ref_key");--> statement-breakpoint
CREATE INDEX "projects_tenancy_idx" ON "projects" ("ref_key","created_at");