-- The AI review on the clock: a status column on `ai_review_runs`, so the
-- reminder tick can read what is still in flight.
--
-- Generated by drizzle-kit from `src/schema.ts`, then EDITED by hand in one
-- place: the column is added nullable, backfilled from the status each row's
-- payload already carries, and only then made NOT NULL. The generated
-- `ADD COLUMN ... NOT NULL` fails on any table that has rows, and a default
-- would have written the same status onto every run regardless of where it
-- actually got to.
--
-- The final schema is exactly what `snapshot.json` records, so the next
-- `db:generate` diffs against the same state drizzle believes this left behind.
-- The D1 adapter carries the same change as `migrations/0004_ai_review_status.sql`.

ALTER TABLE "ai_review_runs" ADD COLUMN "status" text;--> statement-breakpoint
UPDATE "ai_review_runs" SET "status" = "data"->>'status' WHERE "status" IS NULL;--> statement-breakpoint
ALTER TABLE "ai_review_runs" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
-- The reminder tick's AI-review read: what is unsettled in the org it is
-- ticking, oldest request first.
CREATE INDEX "ai_review_runs_status_idx" ON "ai_review_runs" ("org_id","status","requested_at");
