-- The board's ordered reads, given indexes that answer them.
--
-- `GET /reviews` is `WHERE org_id = ? ORDER BY created_at DESC, id DESC LIMIT ?`,
-- with an optional status. Before this, neither shape was covered: the only
-- composite started `(org_id, status, created_at)`, so a read that named no
-- status scanned the org's rows and sorted them, and one that did still needed a
-- sort step for the tie-break, because no index ended in `id`.
--
-- Both indexes are declared DESC to match the order the read asks for. An
-- ascending index can be walked backwards, but the planner then has the far end
-- of the org's history to walk back FROM, and the whole point of the new `LIMIT`
-- on this route is a top-N scan that touches the newest rows and stops.
--
-- The status index is dropped and recreated rather than added beside: it is the
-- same index with the ordering spelled out and the tie-break added, so leaving
-- the old one would keep a second copy of the same key to maintain on every
-- write.
--
-- Generated by drizzle-kit from `src/schema.ts` and committed as generated; the
-- D1 adapter carries the same change as `migrations/0005_board_ordering.sql`.

DROP INDEX "review_requests_status_idx";--> statement-breakpoint
CREATE INDEX "review_requests_status_idx" ON "review_requests" ("org_id","status","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "review_requests_created_idx" ON "review_requests" ("org_id","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);
